768 release deployment
SecureApiGateway/secure-api-gateway-releases-helpers pull request #1
Opened 2023-03-27 13:32 UTC by shaunharrisonFR

Add helper helm charts to repo and a way of creating a release to push to the artifact 

We don't have maven or other packages like we do in our other repos so can't use the release template we use in the parent repo. 

For now the github action is going to be called manually, but once confirmed working can do it so it runs when a tag is created

Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/768

2023-03-27 13:38 UTC, BohoCode reviewed
Do these will also need a release workflow @jorgesanchezperez 

Our aim is to make a specific cluster re-creatable, so we must be able to deploy the same version of all helm charts if possible, so these should also be published into the helm repository. They don't necessarily need to have the same version as the Secure API Gateway.

2023-03-27 13:40 UTC, BohoCode requested changes, later dismissed
Needs a readme.md Shaun ;-)

2023-03-27 13:50 UTC, shaunharrisonFR commented
> Needs a readme.md Shaun ;-)

Updated!

2023-03-28 09:43 UTC, jorgesanchezperez approved these changes

2023-03-28 10:15 UTC, merged